# Generated by Django 4.2 on 2023-04-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WPUser",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                (
                    "user_login",
                    models.CharField(
                        db_column="user_login", max_length=60, unique=True
                    ),
                ),
                ("password", models.CharField(db_column="user_pass", max_length=255)),
                (
                    "user_nicename",
                    models.CharField(db_column="user_nicename", max_length=50),
                ),
                (
                    "user_email",
                    models.CharField(db_column="user_email", max_length=100),
                ),
                ("user_url", models.CharField(db_column="user_url", max_length=100)),
                ("user_registered", models.DateTimeField(db_column="user_registered")),
                (
                    "user_activation_key",
                    models.CharField(db_column="user_activation_key", max_length=255),
                ),
                ("user_status", models.IntegerField(db_column="user_status")),
                (
                    "display_name",
                    models.CharField(db_column="display_name", max_length=250),
                ),
            ],
            options={
                "db_table": "wp_users",
                "managed": False,
            },
        ),
    ]
